import React, { useState, useEffect } from 'react'
import { blink } from '@/blink/client'
import { LanguageContext, LanguageContextType } from './LanguageContext.ts'

interface Translations {
  [key: string]: string
}

const translations: { [lang: string]: Translations } = {
  en: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.licenses': 'License Management',
    'nav.users': 'User Management',
    'nav.invitations': 'User Invitations',
    'nav.declarations': 'Software Declarations',
    'nav.hrm': 'HRM Integration',
    'nav.analytics': 'Analytics & BI',
    'nav.reviews': 'Software Reviews',
    'nav.reports': 'Reports & Audits',
    'nav.notifications': 'Notifications',
    'nav.support': 'Support',
    'nav.settings': 'Settings',
    'nav.adminCenter': 'Admin Center',
    
    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.subtitle': 'Overview of your license management system',
    'dashboard.totalLicenses': 'Total Licenses',
    'dashboard.activeUsers': 'Active Users',
    'dashboard.pendingDeclarations': 'Pending Declarations',
    'dashboard.expiringLicenses': 'Expiring Soon',
    'dashboard.licenseDistribution': 'License Distribution by Vendor',
    'dashboard.licenseUsage': 'License Usage Overview',
    'dashboard.costTrends': 'Monthly Cost Trends',
    'dashboard.recentActivity': 'Recent Activity',
    
    // License Management
    'licenses.title': 'License Management',
    'licenses.subtitle': 'Manage software licenses and assignments',
    'licenses.addLicense': 'Add License',
    'licenses.editLicense': 'Edit License',
    'licenses.deleteLicense': 'Delete License',
    'licenses.confirmDelete': 'Are you sure you want to delete this license?',
    'licenses.softwareName': 'Software Name',
    'licenses.vendor': 'Vendor',
    'licenses.licenseType': 'License Type',
    'licenses.totalLicenses': 'Total Licenses',
    'licenses.usedLicenses': 'Used Licenses',
    'licenses.costPerLicense': 'Cost per License',
    'licenses.expiryDate': 'Expiry Date',
    'licenses.usage': 'Usage',
    'licenses.cost': 'Cost',
    'licenses.filterByStatus': 'Filter by Status',
    'licenses.allStatuses': 'All Statuses',
    'licenses.searchPlaceholder': 'Search licenses by software name or vendor...',
    'licenses.advancedFilters': 'Advanced Filters',
    'licenses.showAdvancedFilters': 'Show Advanced Filters',
    'licenses.hideAdvancedFilters': 'Hide Advanced Filters',
    'licenses.clearAllFilters': 'Clear All Filters',
    'licenses.filterByVendor': 'Filter by Vendor',
    'licenses.filterByLicenseType': 'Filter by License Type',
    'licenses.filterByCost': 'Filter by Cost',
    'licenses.filterByExpiry': 'Filter by Expiry',
    'licenses.allVendors': 'All Vendors',
    'licenses.allLicenseTypes': 'All License Types',
    'licenses.allCostRanges': 'All Cost Ranges',
    'licenses.allExpiryRanges': 'All Expiry Ranges',
    'licenses.costFree': 'Free ($0)',
    'licenses.costLow': 'Low ($1 - $50)',
    'licenses.costMedium': 'Medium ($51 - $200)',
    'licenses.costHigh': 'High ($201 - $500)',
    'licenses.costEnterprise': 'Enterprise ($500+)',
    'licenses.expiryExpired': 'Expired',
    'licenses.expiryExpiringSoon': 'Expiring Soon (30 days)',
    'licenses.expiryExpiring3Months': 'Expiring in 3 months',
    'licenses.expiryActive': 'Active (3+ months)',
    'licenses.expiryNoExpiry': 'No Expiry',
    
    // User Management
    'users.title': 'User Management',
    'users.subtitle': 'Manage users, roles, and permissions',
    'users.addUser': 'Add User',
    'users.editUser': 'Edit User',
    'users.deleteUser': 'Delete User',
    'users.confirmDelete': 'Are you sure you want to delete this user?',
    'users.totalUsers': 'Total Users',
    'users.activeUsers': 'Active Users',
    'users.administrators': 'Administrators',
    'users.employees': 'Employees',
    'users.name': 'Name',
    'users.email': 'Email',
    'users.role': 'Role',
    'users.department': 'Department',
    'users.position': 'Position',
    'users.createdAt': 'Created At',
    'users.filterByRole': 'Filter by Role',
    'users.allRoles': 'All Roles',
    'users.searchPlaceholder': 'Search users by name, email, department, or position...',
    'users.activate': 'Activate',
    'users.deactivate': 'Deactivate',
    'users.advancedFilters': 'Advanced Filters',
    'users.filterByDepartment': 'Filter by Department',
    'users.filterByStatus': 'Filter by Status',
    'users.allDepartments': 'All Departments',
    'users.allStatuses': 'All Statuses',
    'users.activeUsers': 'Active Users',
    'users.inactiveUsers': 'Inactive Users',
    'users.clearAllFilters': 'Clear All Filters',
    'users.showingResults': 'Showing {count} of {total} users',
    
    // Software Declarations
    'declarations.title': 'Software Declarations',
    'declarations.subtitle': 'Employee software usage declarations and approvals',
    'declarations.newDeclaration': 'New Declaration',
    'declarations.totalDeclarations': 'Total Declarations',
    'declarations.pendingReview': 'Pending Review',
    'declarations.approved': 'Approved',
    'declarations.rejected': 'Rejected',
    'declarations.softwareName': 'Software Name',
    'declarations.vendor': 'Vendor',
    'declarations.purpose': 'Purpose',
    'declarations.businessJustification': 'Business Justification',
    'declarations.urgency': 'Urgency',
    'declarations.licenseType': 'License Type',
    'declarations.approve': 'Approve',
    'declarations.reject': 'Reject',
    'declarations.pending': 'Pending',
    'declarations.searchPlaceholder': 'Search declarations by software name, vendor, department, or employee...',
    'declarations.advancedFilters': 'Advanced Filters',
    'declarations.showAdvancedFilters': 'Show Advanced Filters',
    'declarations.hideAdvancedFilters': 'Hide Advanced Filters',
    'declarations.clearAllFilters': 'Clear All Filters',
    'declarations.filterByDepartment': 'Filter by Department',
    'declarations.filterByUrgency': 'Filter by Urgency',
    'declarations.filterByLicenseType': 'Filter by License Type',
    'declarations.allDepartments': 'All Departments',
    'declarations.allUrgencyLevels': 'All Urgency Levels',
    'declarations.allLicenseTypes': 'All License Types',
    'declarations.urgencyHigh': 'High',
    'declarations.urgencyMedium': 'Medium',
    'declarations.urgencyLow': 'Low',
    'declarations.licenseIndividual': 'Individual',
    'declarations.licenseTeam': 'Team',
    'declarations.licenseEnterprise': 'Enterprise',
    'declarations.showingResults': 'Showing {count} of {total} declarations',
    
    // User Invitations
    'invitations.title': 'User Invitations',
    'invitations.subtitle': 'Invite colleagues to join the platform',
    'invitations.inviteUser': 'Invite User',
    'invitations.bulkInvite': 'Bulk Invite',
    'invitations.totalInvitations': 'Total Invitations',
    'invitations.pending': 'Pending',
    'invitations.accepted': 'Accepted',
    'invitations.expired': 'Expired',
    'invitations.email': 'Email',
    'invitations.role': 'Role',
    'invitations.department': 'Department',
    'invitations.position': 'Position',
    'invitations.sentAt': 'Sent At',
    'invitations.expiresAt': 'Expires At',
    'invitations.resend': 'Resend',
    'invitations.cancel': 'Cancel',
    'invitations.copyLink': 'Copy Link',
    'invitations.searchPlaceholder': 'Search invitations by email or department...',
    
    // HRM Integration
    'hrm.title': 'HRM Integration',
    'hrm.subtitle': 'Automate license management with HR systems',
    'hrm.integrations': 'HRM Integrations',
    'hrm.automationRules': 'Automation Rules',
    'hrm.eventHistory': 'Event History',
    'hrm.addIntegration': 'Add Integration',
    'hrm.addRule': 'Add Rule',
    'hrm.activeIntegrations': 'Active Integrations',
    'hrm.totalRules': 'Total Rules',
    'hrm.totalEvents': 'Total Events',
    'hrm.successRate': 'Success Rate',
    'hrm.sync': 'Sync',
    'hrm.test': 'Test',
    'hrm.configure': 'Configure',
    
    // Reports & Audits
    'reports.title': 'Reports & Audits',
    'reports.subtitle': 'Generate reports and monitor compliance',
    'reports.reports': 'Reports',
    'reports.auditTrail': 'Audit Trail',
    'reports.compliance': 'Compliance',
    'reports.newReport': 'New Report',
    'reports.runCheck': 'Run Check',
    'reports.totalReports': 'Total Reports',
    'reports.auditEntries': 'Audit Entries',
    'reports.complianceChecks': 'Compliance Checks',
    'reports.issuesFound': 'Issues Found',
    'reports.generate': 'Generate',
    'reports.download': 'Download',
    'reports.view': 'View',
    
    // Common
    'common.search': 'Search...',
    'common.filter': 'Filter',
    'common.add': 'Add',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.loading': 'Loading...',
    'common.actions': 'Actions',
    'common.status': 'Status',
    'common.active': 'Active',
    'common.inactive': 'Inactive',
    'common.expired': 'Expired',
    'common.expiring': 'Expiring Soon',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.close': 'Close',
    'common.submit': 'Submit',
    'common.update': 'Update',
    'common.create': 'Create',
    'common.view': 'View',
    'common.manage': 'Manage',
    'common.configure': 'Configure',
    'common.refresh': 'Refresh',
    'common.export': 'Export',
    'common.import': 'Import',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.finish': 'Finish',
    
    // Settings
    'settings.title': 'Settings',
    'settings.subtitle': 'Manage system configuration and preferences',
    'settings.system': 'System',
    'settings.notifications': 'Notifications',
    'settings.security': 'Security',
    'settings.integrations': 'Integrations',
    'settings.language': 'Language',
    'settings.organizationName': 'Organization Name',
    'settings.timezone': 'Timezone',
    'settings.dateFormat': 'Date Format',
    'settings.currency': 'Currency',
    'settings.saveSettings': 'Save Settings',
    'settings.languageChanged': 'Language changed successfully! The interface will update.',
    
    // Dashboard specific translations
    totalLicenses: 'Total Licenses',
    activeUsers: 'Active Users',
    pendingDeclarations: 'Pending Declarations',
    expiringSoon: 'Expiring Soon',
    activeSoftwareLicenses: 'Active software licenses',
    licensedUsers: 'Licensed users',
    awaitingReview: 'Awaiting review',
    within30Days: 'Within 30 days',
    licenseDistributionByVendor: 'License Distribution by Vendor',
    numberOfLicensesPerVendor: 'Number of licenses per software vendor',
    licenseUsageOverview: 'License Usage Overview',
    currentUtilizationOfLicenses: 'Current utilization of available licenses',
    licenseCostTrend: 'License Cost Trend',
    monthlySoftwareLicensingCosts: 'Monthly software licensing costs over time',
    quickActions: 'Quick Actions',
    commonTasksAndShortcuts: 'Common tasks and shortcuts',
    addNewLicense: 'Add New License',
    assignLicense: 'Assign License',
    reviewDeclarations: 'Review Declarations',
    generateReport: 'Generate Report',
    addLicense: 'Add License',
    recentActivity: 'Recent Activity',
    latestLicenseManagementActivities: 'Latest license management activities',
    licenseAssigned: 'License assigned',
    declarationSubmitted: 'Declaration submitted',
    licenseExpiring: 'License expiring',
    newUserAdded: 'New user added',
    viewAllActivity: 'View All Activity',

    // Software Reviews translations
    softwareReviews: 'Software Reviews',
    softwareReviewsDescription: 'Share and discover software experiences from your colleagues',
    writeReview: 'Write Review',
    writeNewReview: 'Write New Review',
    shareYourExperienceWithSoftware: 'Share your experience with software to help your colleagues make informed decisions',
    enterSoftwareName: 'Enter software name',
    enterVendorName: 'Enter vendor name',
    usageDuration: 'Usage Duration',
    lessThanOneMonth: 'Less than 1 month',
    oneToSixMonths: '1-6 months',
    sixPlusMonths: '6+ months',
    ratings: 'Ratings',
    overallRating: 'Overall Rating',
    easeOfUse: 'Ease of Use',
    features: 'Features',
    performance: 'Performance',
    valueForMoney: 'Value for Money',
    reviewTitle: 'Review Title',
    enterReviewTitle: 'Enter a brief title for your review',
    reviewText: 'Review Text',
    shareYourDetailedExperience: 'Share your detailed experience with this software',
    pros: 'Pros',
    whatDidYouLike: 'What did you like about this software?',
    cons: 'Cons',
    whatCouldBeImproved: 'What could be improved?',
    wouldRecommendToColleagues: 'I would recommend this software to colleagues',
    submitAnonymously: 'Submit anonymously',
    submitReview: 'Submit Review',
    totalReviews: 'Total Reviews',
    averageRating: 'Average Rating',
    recommendationRate: 'Recommendation Rate',
    uniqueSoftware: 'Unique Software',
    searchReviewsPlaceholder: 'Search reviews by software, vendor, title, or department...',
    allSoftware: 'All Software',
    advancedFilters: 'Advanced Filters',
    minimumRating: 'Minimum Rating',
    allRatings: 'All Ratings',
    stars: 'stars',
    only: 'only',
    department: 'Department',
    allDepartments: 'All Departments',
    clearAllFilters: 'Clear All Filters',
    showingXOfYReviews: 'Showing {{showing}} of {{total}} reviews',
    noReviewsFound: 'No reviews found',
    tryAdjustingFilters: 'Try adjusting your filters to see more reviews.',
    beFirstToWriteReview: 'Be the first to write a review!',
    anonymous: 'Anonymous',
    unknown: 'Unknown',
    recommends: 'Recommends',
    doesNotRecommend: 'Does not recommend',
    value: 'Value',
    usedFor: 'Used for',
  },
  fr: {
    // Navigation
    'nav.dashboard': 'Tableau de bord',
    'nav.licenses': 'Gestion des licences',
    'nav.users': 'Gestion des utilisateurs',
    'nav.invitations': 'Invitations utilisateurs',
    'nav.declarations': 'Déclarations logicielles',
    'nav.hrm': 'Intégration RH',
    'nav.analytics': 'Analyses et BI',
    'nav.reviews': 'Avis logiciels',
    'nav.reports': 'Rapports et audits',
    'nav.notifications': 'Notifications',
    'nav.support': 'Support',
    'nav.settings': 'Paramètres',
    'nav.adminCenter': 'Centre d\'Administration',
    
    // Dashboard
    'dashboard.title': 'Tableau de bord',
    'dashboard.subtitle': 'Aperçu de votre système de gestion des licences',
    'dashboard.totalLicenses': 'Total des licences',
    'dashboard.activeUsers': 'Utilisateurs actifs',
    'dashboard.pendingDeclarations': 'Déclarations en attente',
    'dashboard.expiringLicenses': 'Expire bientôt',
    'dashboard.licenseDistribution': 'Distribution des licences par fournisseur',
    'dashboard.licenseUsage': 'Aperçu de l\'utilisation des licences',
    'dashboard.costTrends': 'Tendances des coûts mensuels',
    'dashboard.recentActivity': 'Activité récente',
    
    // License Management
    'licenses.title': 'Gestion des licences',
    'licenses.subtitle': 'Gérer les licences logicielles et les attributions',
    'licenses.addLicense': 'Ajouter une licence',
    'licenses.editLicense': 'Modifier la licence',
    'licenses.deleteLicense': 'Supprimer la licence',
    'licenses.confirmDelete': 'Êtes-vous sûr de vouloir supprimer cette licence ?',
    'licenses.softwareName': 'Nom du logiciel',
    'licenses.vendor': 'Fournisseur',
    'licenses.licenseType': 'Type de licence',
    'licenses.totalLicenses': 'Total des licences',
    'licenses.usedLicenses': 'Licences utilisées',
    'licenses.costPerLicense': 'Coût par licence',
    'licenses.expiryDate': 'Date d\'expiration',
    'licenses.usage': 'Utilisation',
    'licenses.cost': 'Coût',
    'licenses.filterByStatus': 'Filtrer par statut',
    'licenses.allStatuses': 'Tous les statuts',
    'licenses.searchPlaceholder': 'Rechercher des licences par nom de logiciel ou fournisseur...',
    'licenses.advancedFilters': 'Filtres avancés',
    'licenses.showAdvancedFilters': 'Afficher les filtres avancés',
    'licenses.hideAdvancedFilters': 'Masquer les filtres avancés',
    'licenses.clearAllFilters': 'Effacer tous les filtres',
    'licenses.filterByVendor': 'Filtrer par fournisseur',
    'licenses.filterByLicenseType': 'Filtrer par type de licence',
    'licenses.filterByCost': 'Filtrer par coût',
    'licenses.filterByExpiry': 'Filtrer par expiration',
    'licenses.allVendors': 'Tous les fournisseurs',
    'licenses.allLicenseTypes': 'Tous les types',
    'licenses.allCostRanges': 'Toutes les gammes de prix',
    'licenses.allExpiryRanges': 'Toutes les dates d\'expiration',
    'licenses.costFree': 'Gratuit (0€)',
    'licenses.costLow': 'Faible (1€ - 50€)',
    'licenses.costMedium': 'Moyen (51€ - 200€)',
    'licenses.costHigh': 'Élevé (201€ - 500€)',
    'licenses.costEnterprise': 'Entreprise (500€+)',
    'licenses.expiryExpired': 'Expiré',
    'licenses.expiryExpiringSoon': 'Expire bientôt (30 jours)',
    'licenses.expiryExpiring3Months': 'Expire dans 3 mois',
    'licenses.expiryActive': 'Actif (plus de 3 mois)',
    'licenses.expiryNoExpiry': 'Pas d\'expiration',
    
    // User Management
    'users.title': 'Gestion des utilisateurs',
    'users.subtitle': 'Gérer les utilisateurs, rôles et permissions',
    'users.addUser': 'Ajouter un utilisateur',
    'users.editUser': 'Modifier l\'utilisateur',
    'users.deleteUser': 'Supprimer l\'utilisateur',
    'users.confirmDelete': 'Êtes-vous sûr de vouloir supprimer cet utilisateur ?',
    'users.totalUsers': 'Total des utilisateurs',
    'users.activeUsers': 'Utilisateurs actifs',
    'users.administrators': 'Administrateurs',
    'users.employees': 'Employés',
    'users.name': 'Nom',
    'users.email': 'Email',
    'users.role': 'Rôle',
    'users.department': 'Département',
    'users.position': 'Poste',
    'users.createdAt': 'Créé le',
    'users.filterByRole': 'Filtrer par rôle',
    'users.allRoles': 'Tous les rôles',
    'users.searchPlaceholder': 'Rechercher des utilisateurs par nom, email, département ou poste...',
    'users.activate': 'Activer',
    'users.deactivate': 'Désactiver',
    'users.advancedFilters': 'Filtres avancés',
    'users.filterByDepartment': 'Filtrer par département',
    'users.filterByStatus': 'Filtrer par statut',
    'users.allDepartments': 'Tous les départements',
    'users.allStatuses': 'Tous les statuts',
    'users.activeUsers': 'Utilisateurs actifs',
    'users.inactiveUsers': 'Utilisateurs inactifs',
    'users.clearAllFilters': 'Effacer tous les filtres',
    'users.showingResults': 'Affichage de {count} sur {total} utilisateurs',
    
    // Software Declarations
    'declarations.title': 'Déclarations logicielles',
    'declarations.subtitle': 'Déclarations d\'utilisation de logiciels par les employés et approbations',
    'declarations.newDeclaration': 'Nouvelle déclaration',
    'declarations.totalDeclarations': 'Total des déclarations',
    'declarations.pendingReview': 'En attente d\'examen',
    'declarations.approved': 'Approuvées',
    'declarations.rejected': 'Rejetées',
    'declarations.softwareName': 'Nom du logiciel',
    'declarations.vendor': 'Fournisseur',
    'declarations.purpose': 'Objectif',
    'declarations.businessJustification': 'Justification métier',
    'declarations.urgency': 'Urgence',
    'declarations.licenseType': 'Type de licence',
    'declarations.approve': 'Approuver',
    'declarations.reject': 'Rejeter',
    'declarations.pending': 'En attente',
    'declarations.searchPlaceholder': 'Rechercher des déclarations par nom de logiciel, fournisseur, département ou employé...',
    'declarations.advancedFilters': 'Filtres avancés',
    'declarations.showAdvancedFilters': 'Afficher les filtres avancés',
    'declarations.hideAdvancedFilters': 'Masquer les filtres avancés',
    'declarations.clearAllFilters': 'Effacer tous les filtres',
    'declarations.filterByDepartment': 'Filtrer par département',
    'declarations.filterByUrgency': 'Filtrer par urgence',
    'declarations.filterByLicenseType': 'Filtrer par type de licence',
    'declarations.allDepartments': 'Tous les départements',
    'declarations.allUrgencyLevels': 'Tous les niveaux d\'urgence',
    'declarations.allLicenseTypes': 'Tous les types de licence',
    'declarations.urgencyHigh': 'Élevée',
    'declarations.urgencyMedium': 'Moyenne',
    'declarations.urgencyLow': 'Faible',
    'declarations.licenseIndividual': 'Individuelle',
    'declarations.licenseTeam': 'Équipe',
    'declarations.licenseEnterprise': 'Entreprise',
    'declarations.showingResults': 'Affichage de {count} sur {total} déclarations',
    
    // User Invitations
    'invitations.title': 'Invitations utilisateurs',
    'invitations.subtitle': 'Inviter des collègues à rejoindre la plateforme',
    'invitations.inviteUser': 'Inviter un utilisateur',
    'invitations.bulkInvite': 'Invitation en masse',
    'invitations.totalInvitations': 'Total des invitations',
    'invitations.pending': 'En attente',
    'invitations.accepted': 'Acceptées',
    'invitations.expired': 'Expirées',
    'invitations.email': 'Email',
    'invitations.role': 'Rôle',
    'invitations.department': 'Département',
    'invitations.position': 'Poste',
    'invitations.sentAt': 'Envoyé le',
    'invitations.expiresAt': 'Expire le',
    'invitations.resend': 'Renvoyer',
    'invitations.cancel': 'Annuler',
    'invitations.copyLink': 'Copier le lien',
    'invitations.searchPlaceholder': 'Rechercher des invitations par email ou département...',
    
    // HRM Integration
    'hrm.title': 'Intégration RH',
    'hrm.subtitle': 'Automatiser la gestion des licences avec les systèmes RH',
    'hrm.integrations': 'Intégrations RH',
    'hrm.automationRules': 'Règles d\'automatisation',
    'hrm.eventHistory': 'Historique des événements',
    'hrm.addIntegration': 'Ajouter une intégration',
    'hrm.addRule': 'Ajouter une règle',
    'hrm.activeIntegrations': 'Intégrations actives',
    'hrm.totalRules': 'Total des règles',
    'hrm.totalEvents': 'Total des événements',
    'hrm.successRate': 'Taux de réussite',
    'hrm.sync': 'Synchroniser',
    'hrm.test': 'Tester',
    'hrm.configure': 'Configurer',
    
    // Reports & Audits
    'reports.title': 'Rapports et audits',
    'reports.subtitle': 'Générer des rapports et surveiller la conformité',
    'reports.reports': 'Rapports',
    'reports.auditTrail': 'Piste d\'audit',
    'reports.compliance': 'Conformité',
    'reports.newReport': 'Nouveau rapport',
    'reports.runCheck': 'Exécuter la vérification',
    'reports.totalReports': 'Total des rapports',
    'reports.auditEntries': 'Entrées d\'audit',
    'reports.complianceChecks': 'Vérifications de conformité',
    'reports.issuesFound': 'Problèmes trouvés',
    'reports.generate': 'Générer',
    'reports.download': 'Télécharger',
    'reports.view': 'Voir',
    
    // Common
    'common.search': 'Rechercher...',
    'common.filter': 'Filtrer',
    'common.add': 'Ajouter',
    'common.edit': 'Modifier',
    'common.delete': 'Supprimer',
    'common.save': 'Enregistrer',
    'common.cancel': 'Annuler',
    'common.loading': 'Chargement...',
    'common.actions': 'Actions',
    'common.status': 'Statut',
    'common.active': 'Actif',
    'common.inactive': 'Inactif',
    'common.expired': 'Expiré',
    'common.expiring': 'Expire bientôt',
    'common.yes': 'Oui',
    'common.no': 'Non',
    'common.close': 'Fermer',
    'common.submit': 'Soumettre',
    'common.update': 'Mettre à jour',
    'common.create': 'Créer',
    'common.view': 'Voir',
    'common.manage': 'Gérer',
    'common.configure': 'Configurer',
    'common.refresh': 'Actualiser',
    'common.export': 'Exporter',
    'common.import': 'Importer',
    'common.back': 'Retour',
    'common.next': 'Suivant',
    'common.previous': 'Précédent',
    'common.finish': 'Terminer',
    
    // Settings
    'settings.title': 'Paramètres',
    'settings.subtitle': 'Gérer la configuration système et les préférences',
    'settings.system': 'Système',
    'settings.notifications': 'Notifications',
    'settings.security': 'Sécurité',
    'settings.integrations': 'Intégrations',
    'settings.language': 'Langue',
    'settings.organizationName': 'Nom de l\'organisation',
    'settings.timezone': 'Fuseau horaire',
    'settings.dateFormat': 'Format de date',
    'settings.currency': 'Devise',
    'settings.saveSettings': 'Enregistrer les paramètres',
    'settings.languageChanged': 'Langue modifiée avec succès ! L\'interface va se mettre à jour.',

    // Software Reviews translations
    softwareReviews: 'Avis logiciels',
    softwareReviewsDescription: 'Partagez et découvrez les expériences logicielles de vos collègues',
    writeReview: 'Écrire un avis',
    writeNewReview: 'Écrire un nouvel avis',
    shareYourExperienceWithSoftware: 'Partagez votre expérience avec ce logiciel pour aider vos collègues à prendre des décisions éclairées',
    enterSoftwareName: 'Entrez le nom du logiciel',
    enterVendorName: 'Entrez le nom du fournisseur',
    usageDuration: 'Durée d\'utilisation',
    lessThanOneMonth: 'Moins d\'un mois',
    oneToSixMonths: '1-6 mois',
    sixPlusMonths: '6+ mois',
    ratings: 'Évaluations',
    overallRating: 'Évaluation globale',
    easeOfUse: 'Facilité d\'utilisation',
    features: 'Fonctionnalités',
    performance: 'Performance',
    valueForMoney: 'Rapport qualité-prix',
    reviewTitle: 'Titre de l\'avis',
    enterReviewTitle: 'Entrez un titre bref pour votre avis',
    reviewText: 'Texte de l\'avis',
    shareYourDetailedExperience: 'Partagez votre expérience détaillée avec ce logiciel',
    pros: 'Avantages',
    whatDidYouLike: 'Qu\'avez-vous aimé dans ce logiciel ?',
    cons: 'Inconvénients',
    whatCouldBeImproved: 'Qu\'est-ce qui pourrait être amélioré ?',
    wouldRecommendToColleagues: 'Je recommanderais ce logiciel à mes collègues',
    submitAnonymously: 'Soumettre anonymement',
    submitReview: 'Soumettre l\'avis',
    totalReviews: 'Total des avis',
    averageRating: 'Note moyenne',
    recommendationRate: 'Taux de recommandation',
    uniqueSoftware: 'Logiciels uniques',
    searchReviewsPlaceholder: 'Rechercher des avis par logiciel, fournisseur, titre ou département...',
    allSoftware: 'Tous les logiciels',
    advancedFilters: 'Filtres avancés',
    minimumRating: 'Note minimum',
    allRatings: 'Toutes les notes',
    stars: 'étoiles',
    only: 'seulement',
    department: 'Département',
    allDepartments: 'Tous les départements',
    clearAllFilters: 'Effacer tous les filtres',
    showingXOfYReviews: 'Affichage de {{showing}} sur {{total}} avis',
    noReviewsFound: 'Aucun avis trouvé',
    tryAdjustingFilters: 'Essayez d\'ajuster vos filtres pour voir plus d\'avis.',
    beFirstToWriteReview: 'Soyez le premier à écrire un avis !',
    anonymous: 'Anonyme',
    unknown: 'Inconnu',
    recommends: 'Recommande',
    doesNotRecommend: 'Ne recommande pas',
    value: 'Valeur',
    usedFor: 'Utilisé pendant',
  }
}



export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState('en')
  const [isLoading, setIsLoading] = useState(true)

  useEffect(() => {
    // Load language from system settings
    const loadLanguage = async () => {
      try {
        const systemData = await blink.db.systemSettings.list({ limit: 1 })
        if (systemData.length > 0) {
          const savedLanguage = systemData[0].language || 'en'
          setLanguageState(savedLanguage)
        }
      } catch (error) {
        console.error('Error loading language setting:', error)
      } finally {
        setIsLoading(false)
      }
    }
    
    loadLanguage()
  }, [])

  const setLanguage = async (lang: string) => {
    try {
      setLanguageState(lang)
      
      // Update system settings with new language
      const systemData = await blink.db.systemSettings.list({ limit: 1 })
      if (systemData.length > 0) {
        await blink.db.systemSettings.update(systemData[0].id, { language: lang })
      }
    } catch (error) {
      console.error('Error saving language setting:', error)
    }
  }

  const t = (key: string): string => {
    return translations[language]?.[key] || translations['en']?.[key] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isLoading }}>
      {children}
    </LanguageContext.Provider>
  )
}

